import { LiveDataProps } from "./components/CardList";

export const liveDataPropsArray: LiveDataProps[] = [
    {
      id: "1",
      deadlineDate: "2024-01-01",
      name: "Elon Musk",
      age: "52",
      description: "CEO of SpaceX, Tesla Inc., Neuralink, and The Boring Company.",
      industry: "Tech/Entrepreneurship",
      goal: "Advancing humanity through technology and space exploration.",
      image: "/images/Elon.png",
      deadline: "2023-12-31",
      twitterUrl: "https://twitter.com/elonmusk",
      youtubeUrl: "https://youtube.com/user/spacexchannel",
    },
    {
      id: "2",
      deadlineDate: "2024-01-01",
      name: "Gary Vaynerchuk",
      age: "47",
      description: "Chairman of VaynerX, CEO of VaynerMedia, and a popular public speaker.",
      industry: "Marketing/Entrepreneurship",
      goal: "Helping businesses navigate the digital landscape.",
      image: "/images/GaryV.jpg",
      deadline: "2023-12-31",
      linkedInUrl: "https://linkedin.com/in/garyvaynerchuk",
      twitterUrl: "https://twitter.com/garyvee",
      instagramUrl: "https://instagram.com/garyvee",
      youtubeUrl: "https://youtube.com/user/GaryVaynerchuk",
    },
    {
      id: "3",
      deadlineDate: "2024-01-01",
      name: "Cristiano Ronaldo",
      age: "38",
      description: "Professional footballer who plays as a forward for Manchester United and the Portugal national team.",
      industry: "Sports/Football",
      goal: "Being one of the best footballers in the world.",
      image: "/images/ronaldo.jpg",
      deadline: "2023-12-31",
      twitterUrl: "https://twitter.com/Cristiano",
      instagramUrl: "https://instagram.com/cristiano",
    },
    {
      id: "4",
      deadlineDate: "2024-01-01",
      name: "Marques Brownlee",
      age: "29",
      description: "American YouTuber best known for his technology-focused videos.",
      industry: "Tech/YouTube",
      goal: "Reviewing and explaining the latest tech products.",
      image: "/images/mkbhd.jpg",
      deadline: "2023-12-31",
      twitterUrl: "https://twitter.com/MKBHD",
      instagramUrl: "https://instagram.com/mkbhd",
      youtubeUrl: "https://youtube.com/user/marquesbrownlee",
    },
    {
      id: "5",
      deadlineDate: "2024-01-01",
      name: "Satya Nadella",
      age: "55",
      description: "CEO of Microsoft.",
      industry: "Tech",
      goal: "Leading Microsoft into the new era of cloud computing.",
      image: "/images/Satya.webp",
      deadline: "2023-12-31",
      linkedInUrl: "https://linkedin.com/in/satyanadella",
      twitterUrl: "https://twitter.com/satyanadella",
    },
    {
      id: "6",
      deadlineDate: "2024-01-01",
      name: "Sundar Pichai",
      age: "50",
      description: "CEO of Alphabet and Google.",
      industry: "Tech",
      goal: "Steering Google through the next phase of innovation and growth.",
      image: "/images/google.webp",
      deadline: "2023-12-31",
      linkedInUrl: "https://linkedin.com/in/sundarpichai",
      twitterUrl: "https://twitter.com/sundarpichai",
    },
    {
      id: "7",
      deadlineDate: "2024-01-01",
      name: "Justine Ezarik",
      age: "38",
      description: "American YouTuber, host, author, and actress. Known as iJustine on YouTube.",
      industry: "Tech/YouTube",
      goal: "Creating tech-focused videos and entertainment content.",
      image: "/images/justine.jpg",
      deadline: "2023-12-31",
      instagramUrl: "https://instagram.com/ijustine",
      youtubeUrl: "https://youtube.com/user/ijustine",
    },
    {
      id: "8",
      deadlineDate: "2024-01-01",
      name: "Brene Brown",
      age: "57",
      description: "Research professor, author, and public speaker. Known for her work on vulnerability, courage, empathy, and shame.",
      industry: "Education/Personal Development",
      goal: "Helping people understand the power of vulnerability and empathy.",
      image: "/images/brownlede.webp",
      deadline: "2023-12-31",
      linkedInUrl: "https://linkedin.com/in/brene-brown-8b10583",
      twitterUrl: "https://twitter.com/BreneBrown",
      instagramUrl: "https://instagram.com/brenebrown",
      youtubeUrl: "", // Brene Brown doesn't have an official YouTube channel
    }
    ];
  